[build]
  base = "Quanta_meditation/"
  publish = "client/build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "14.17.0"

[[redirects]]
  from = "Quanta_meditation/*"
  to = "/blog/:splat"
  #to = "/index.html"
  status = 200
