[build]
  base = "Quanta_meditation/"
  publish = "client/build"
  command = "npm run build"

[context.production]
  publish = "output/"
  command = "make publish"
  environment = { NODE_VERSION = "14.15.3" }

[[redirects]]
  from = "/*"
  to = "/blog/:splat"
  status = 200
