name: Update Index

on:
  push:
    branches: [main]
    paths:
      - 'Beginning of Infinity/**'
      - 'Mindfullness/**'
      - 'Quantum Physics Simulations/**'
  workflow_dispatch:

jobs:
  update-index:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: List directory contents
      run: ls -R
    - name: Generate index.html
      run: python generate_index.py
    - name: Display index.html content
      run: cat index.html
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add index.html
        git diff --staged --quiet || git commit -m "Update index.html"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.ACTIONS_PAT }}
        branch: ${{ github.ref }}
